export interface Session {
    Radacctid: number,
    Acctsessionid: string,
    Acctuniqueid: string,
    Username: string,
    Groupname: string,
    Realm: string | null,
    Nasipaddress: string,
    Nasidentifier: string,
    Nasportid: string | null,
    Nasporttype: string | null,
    Acctstarttime: Date | null,
    Acctupdatetime: Date | null,
    Acctstoptime: Date | null,
    Acctinterval: number | null,
    Acctsessiontime: number | null,
    Acctauthentic: string | null,
    ConnectinfoStart: string | null,
    ConnectinfoStop: string | null,
    Acctinputoctets: number | null,
    Acctoutputoctets: number | null,
    Calledstationid: string,
    Callingstationid: string,
    Acctterminatecause: string,
    Servicetype: string | null,
    Framedprotocol: string | null,
    Framedipaddress: string,
    Acctstartdelay: number | null,
    Acctstopdelay: number | null,
    Xascendsessionsvrkey: string | null
}