export interface Server {
    id: number,
    nasname: string,
    shortname: string | null,
    nasidentifier: string,
    type: string | null,
    ports: number | null,
    secret: string,
    server: string | null,
    community: string | null,
    description: string | null,
    connectionType: string | null,
    timezone: string,
    recordAuth: boolean,
    ignoreAcct: boolean,
    dynamicAttribute: string,
    dynamicValue: string,
    monitor: string | null,
    pingInterval: number,
    heartbeatDeadAfter: number,
    lastContact: Date | null,
    sessionAutoClose: boolean,
    sessionDeadTime: number,
    onPublicMaps: boolean,
    lat: number | null,
    lon: number | null,
    photoFileName: string,
    cloudId: number | null,
    created: Date,
    modified: Date
}
