import { UIColors } from "../components"

export interface User {
    id: number,
    username: string,
    password: string,
    token: string | null,
    name: string | null,
    surname: string | null,
    address: string | null,
    phone: string | null,
    email: string | null,
    authType: string,
    active: boolean,
    lastAcceptTime: Date | null,
    lastRejectTime: Date | null,
    lastAcceptNas: string | null,
    lastRejectNas: string | null,
    lastRejectMessage: string | null,
    percTimeUsed: number | null,
    percDataUsed: number | null,
    dataUsed: number | null,
    dataCap: number | null,
    timeUsed: number | null,
    timeCap: number | null,
    timeCapType: string | null,
    dataCapType: string | null,
    realm: string | null,
    realmId: number | null,
    profile: string | null,
    profileId: number | null,
    fromDate: Date | null,
    toDate: Date | null,
    trackAuth: boolean,
    trackAcct: boolean | null,
    staticIp: string | null,
    extraName: string | null,
    extraValue: string | null,
    countryId: number | null,
    languageId: number | null,
    cloudId: number | null,
    created: Date,
    modified: Date
}

export interface PermanentUserPlan {
    permanentUserId: number,
    validTime: Date,
    profileId: number,
    overridePrice: number | null,
    created: Date,
}

export interface Membership {
    planId: number,
    profileId: number,
    name: string,
    validTime: Date,
    price: number,
    color: UIColors,
    created: Date,
    modified: Date,
}